const checkUserAuthentication = (val: number) => {
  return 2;
};

export enum authenticationEnum {
  Super_Admin = 1,
  Home_Dashboard = 2,
  Member_Dashboard = 3,
  System_Privileges = 4,
  Privilege_Groups = 5,
  Trainer_Login = 6,
  Member_Login = 7,
  Employee_Registration = 8,
  Member_Registration = 9,
  Mark_Attendance = 10,
  Assign_Trainer = 11,
  Manage_Exercises = 12,
  Workout_Templates = 13,
  Workout_Plan_Request = 14,
  Pending_Requests = 15,
  My_Workout_Plans = 16,
  Progress_Tracking = 17,
  Member_Progress = 18,
  Schedule_Class = 19,
  Book_Class = 20,
  My_Bookings = 21,
  Manage_Food_Items = 22,
  Meal_Plan_Templates = 23,
  Assign_Meal_Plan = 24,
  Nutrition_And_Meal_Plan = 25,
  Goal_Based_Calorie_Target = 26,
  Inventory_Management = 27,
  Sales_And_Requests = 28,
  Browse_Suplements = 29,
  For_Your_Approval = 30,
  Equipments = 31,
  Suppliers = 32,
  Membership_Categories = 33,
  Reports = 34,
  Payments = 35,
  Ratings_And_Feedback = 36,
  Feedback_History = 37,
}
