const checkUserAuthentication = (val: number) => {
  return 2;
};

export enum authenticationEnum {
  Super_Admin = 1,
  Home_Dashboard = 2,
  Member_Dashboard = 3,
  System_Privileges = 4,
  Privilege_Groups = 5,
  Trainer_Login = 6,
  Member_Login = 7,
  Employee_Registration = 8,
  Member_Registration = 9,
  Mark_Attendance = 10,
  Assign_Trainer = 11,
  Manage_Exercises = 12,
  Workout_Templates = 13,
  Workout_Plan_Request = 14,
  Pending_Requests = 15,
  My_Workout_Plans = 16,
  Progress_Tracking = 17,
  Member_Progress = 18,
  Schedule_Class = 19,
  Book_Class = 20,
  Nutrition_And_Meal_Plan = 21,
  Goal_Based_Calorie_Target = 22,
  Upload_Nutrition_Meal_Plan = 23,
  Inventory_Management = 24,
  Sales_And_Requests = 25,
  Browse_Suplements = 26,
  For_Your_Approval = 27,
  Equipments = 28,
  Suppliers = 29,
  Membership_Categories = 30,
  Reports = 31,
  Payments = 32,
  Ratings_And_Feedback = 33,
  Feedback_History = 34,
  My_Bookings = 35,
}
